# Elasticsearch configuration for development environment

# Cluster settings
cluster:
  name: my-application-cluster

# Node settings
node:
  name: node-1

# Network settings
network:
  host: 0.0.0.0

# HTTP settings
http:
  port: 9200

# Discovery settings
discovery:
  type: single-node

# Memory settings
bootstrap:
  memory_lock: true


# Path settings
path:
  data: /usr/share/elasticsearch/data
  logs: /usr/share/elasticsearch/logs

# Security settings (disabled for development)
xpack.security.enabled: false

# Allow CORS for development
http.cors.enabled: true
http.cors.allow-origin: "*"

# Increase the merge thread pool size
thread_pool.write.queue_size: 1000

